create table if not exists public.digemid_norma_assets (
  id bigint generated by default as identity primary key,
  norma_id uuid not null references public.digemid_normas(id) on delete cascade,
  page_id uuid references public.digemid_norma_paginas(id) on delete set null,
  asset_tipo text not null,
  asset_subtipo text,
  storage_backend text not null default 'google_drive',
  storage_path text,
  drive_file_id text,
  source_url text,
  mime_type text,
  file_name text,
  file_ext text,
  file_size_bytes bigint,
  page_number integer,
  bbox jsonb not null default '{}'::jsonb,
  text_hint text,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists digemid_norma_assets_norma_id_idx
  on public.digemid_norma_assets (norma_id);

create index if not exists digemid_norma_assets_page_id_idx
  on public.digemid_norma_assets (page_id);

create index if not exists digemid_norma_assets_asset_tipo_idx
  on public.digemid_norma_assets (asset_tipo);

create index if not exists digemid_norma_assets_asset_subtipo_idx
  on public.digemid_norma_assets (asset_subtipo);

create index if not exists digemid_norma_assets_drive_file_id_idx
  on public.digemid_norma_assets (drive_file_id);

create index if not exists digemid_norma_assets_page_number_idx
  on public.digemid_norma_assets (page_number);

create unique index if not exists digemid_norma_assets_norma_tipo_subtipo_file_uidx
  on public.digemid_norma_assets (
    norma_id,
    asset_tipo,
    coalesce(asset_subtipo, ''),
    file_name
  )
  where file_name is not null;

grant usage on schema public to service_role;
grant all privileges on table public.digemid_norma_assets to service_role;

comment on table public.digemid_norma_assets is
'Tabla del modulo normativo DIGEMID para PDF original, manifest, imagenes renderizadas, tablas detectadas, anexos, OCR artifacts y archivos derivados. No reemplaza digemid_norma_paginas ni digemid_norma_chunks.';

