name: Deploy Supabase Functions

on:
  workflow_dispatch:

  push:
    branches:
      - main
    paths:
      - "supabase/functions/**"
      - ".github/workflows/deploy-supabase-functions.yml"

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
      PROJECT_ID: ${{ secrets.SUPABASE_PROJECT_REF }}

    steps:
      - name: Descargar repositorio
        uses: actions/checkout@v4

      - name: Configurar Supabase CLI
        uses: supabase/setup-cli@v1
        with:
          version: latest

      - name: Desplegar función telegram-bot
        run: supabase functions deploy telegram-bot --project-ref $PROJECT_ID
